### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Raileanv** [aristofun/azbuker#10]
https://github.com/aristofun/azbuker/blob/0a4aab56ee0485ec11a08effdc08bb633a4c22ab/app/models/book.rb#L8
`size == '/criginal'` - looks like it should be `original` instead of `criginal`

**Comment by aristofun** [comment]
чуть выше строчка, которая первый символ убирает, для однообразия, 
норм все (попробуйте на локально воспроизвести)
